version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio
    volumes:
      - ./studio/layout.json:/src/layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros:${ROS_DISTRO}-rosbridge-suite
    ports:
      - 9090:9090
    restart: always
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  ros-lis3dh:
    image: ghcr.io/rosblox/ros:${ROS_DISTRO}-lis3dh
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: always
    network_mode: "host"
    privileged: true
    command: ros2 run blox_lis3dh blox_lis3dh_publisher
